### PR TITLE
Update and rename test.yml to ci.yml

### PR DESCRIPTION
**Pull request by dark-enstein**
- Fixed indentation issues with Test step run by;
- Seperated checkout step from test step

### CODE REVIEW

**Comment by dark-enstein** [comment]
@opensaucerer This should fix the current issues with the passed in env variables in the ci workflow.

**Comment by dark-enstein** [comment]
Though curious, why do we need these credentials to test and build?

**Comment by opensaucerer** [comment]
We're working with cloud providers and we need to authenticate with these providers to ensure our functions work on implementation level. 

Before.. merging I think we should keep it as test.yml because more ci configs will come overtime and it's best to separate their and clearly state their work.

**Comment by dark-enstein** [comment]
Alright. done

**Comment by dark-enstein** [comment]
Damn, need to add a dependency between the jobs; both shouldn't run concurrently. I'll schedule that for the next patch later

**Pull request merged**
