### PR TITLE
add useAsync bool field to config structs

### PR DESCRIPTION
**Pull request by Emmrys-Jay**
## Tasks

- Added UseAsync field to config structs for each available cloud service.
- Added the UseAsync field to the Config method of the struct for gcs and newGoogleCloudStorage function.

### CODE REVIEW

**Review by opensaucerer — COMMENTED** [review]
Awesome update. 
I just thought of something we'll need again now.
Here's the idea, when a user enables async operations, we'll need to signal to them when the operation is done. We need to return a channel in the `UploadFile` struct. Other future structs will also implement this format. 
The channel simply needs to be a bool channel called `Done`

We also need another channel called `Quit`. This channel can be used by the user to signal back to us if they need to cancel the running async process. 

Now, with this `UseAsync`, it should be clear that we need to change the return type of `UploadFile` from `UploadedFile` to a pointer `*UploadedFile`. This is because initially after a file is uploaded with async enabled, we'll need to return the struct to them but without all the data filled in yet. So, after the upload completes, we can be able to update that same return value such that they also get the update as well...only pointers allow for this. 

### summary
##### New fields in UploadedFile
- Done (channel) // Done sends a message to signal when an async process is complete
- Quit (channel) // Quite receives a message to signal for the exit of an async process
##### Modify the return type of `UploadFile` to a struct pointer. This requires a change to the `rainbowBridge` interface as well.

**Comment by Emmrys-Jay** [comment]
Alright, thanks.

I'll work on that.

**Comment by Emmrys-Jay** [comment]
Hi @opensaucerer 

I've made the new changes.

**Comment by opensaucerer** [comment]
LGTM

**Comment by Emmrys-Jay** [comment]
Thanks chief 🙏

I'll work on integrating web3.storage after this.

**Pull request merged**
