### PR TITLE
add ci workflow to build and test go files

### PR DESCRIPTION
**Pull request by dark-enstein**
Note: currently most tests do not pass, and that will need to be worked on

### CODE REVIEW

**Comment by opensaucerer** [comment]
> Note: currently most tests do not pass, and that will need to be worked on

Thank you for this contribution @dark-enstein 
But I just want to clarify, when you say most tests don't pass...are you referring to the workflow not working well or the tests in the code not working well?

This is because you might be missing the required environment variables. 

Nonetheless, I made an update to the MR and added the secrets and env...hopefully, everything goes well.

**Comment by dark-enstein** [comment]
Awesome. Thank you. 

What I meant is that the test written currently in the code on running `go test`. I'm sure you see it in the current workflow runs @opensaucerer

**Comment by opensaucerer** [comment]
Yeah... that's because you're missing some env values. I've added the secrets. Now 2/3 providers tests pass. 

The last one is failing due to file path issues. I'm not home currently so I can't look into it well but you can definitely push a PR to patch that. You can check the last run to see the error.

**Comment by dark-enstein** [comment]
I'll take a look at the file path issue. I noticed in the last run that there were indentation issues with the referenced secrets, and so the secret refs were read literally, and not substituted for the actual secret. Fixed that in a new PR

**Pull request merged**
